version: "3.3"

volumes:
  pgdata:

services:
  processing:
    build:
      context: .
      dockerfile: docker/processing/Dockerfile
    command: python manage.py gm_worker_processing --queue process_sound
    depends_on:
      - db
    env_file:
     - .env
 
  web:
    build:
      context: .

    env_file:
     - .env
    volumes:
     - .:/code

    ports:
     - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:9.6
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
     - .env
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=freesound
